services:
  anonymous_db:
    image: postgres:15
    container_name: anonymous_postgres_container
    restart: always
    environment:
      POSTGRES_USER: user_anon
      POSTGRES_PASSWORD: password_anon
      POSTGRES_DB: anonymous_app_db
    ports:
      - "5433:5432" # Changed local port to 5433 to avoid conflict with standard Postgres
    volumes:
      - anonymous_pg_data:/var/lib/postgresql/data

volumes:
  anonymous_pg_data: